In [1]:
import torch 
print(torch.__version__)

2.1.2+cpu


## Creating Tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,8],[9,10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[0][0]

tensor(7)

In [14]:
matrix[1][0]

tensor(9)

In [15]:
TENSOR = torch.tensor([[[2,3,1],[4,5,1],[6,7,1]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])